version: "3.9"

services:
  redis:
    container_name: redis
    environment:
      - REDIS_UPSTREAM_IP=${REDIS_UPSTREAM_IP}
      - REDIS_UPSTREAM_PORT=${REDIS_UPSTREAM_PORT}
      - REDIS_UPSTREAM_PASSWORD=${REDIS_UPSTREAM_PASSWORD}
    build: redis
    ports:
      - 6381:6381
    restart: always
    sysctls:
      - net.core.somaxconn=512
    networks:
      - redis_net
  datadog:
    container_name: datadog
    build: datadog
    links:
      - redis
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_AGENT_HOST=${DD_AGENT_HOST}
      - DD_CONTAINER_INCLUDE="redis, monitor"
      - DD_CONTAINER_INCLUDE_METRICS="redis, monitor"
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOG_LEVEL=error
    networks:
      - redis_net
  monitor:
    container_name: monitor
    build: monitor
    links:
      - redis
      - datadog
    environment:
      - STATSD_HOST="datadog"
    networks:
      - redis_net
networks:
  redis_net:
    driver: bridge
